common:
  lidar_topic:  "/uav_160/livox/lidar"
  imu_topic:  "/uav_160/livox/imu"
  IMU_INIT_COUNT: 200

preprocess:
  lidar_type: 2              
  scan_line: 4
  blind: 0.3

mapping:
  acc_cov: 0.001
  gyr_cov: 0.0001
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  fov_degree: 360
  det_range:  80.0
  extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
  extrinsic_T: [-0.011, -0.02329, 0.04412]  # Lidar在IMU坐标系中的位置
  extrinsic_R: [1, 0, 0,  # 从LiDAR坐标系旋转到IMU坐标系的旋转矩阵
                0, 1, 0,
                0, 0, 1]
  lidar2base_T: [0, 0, 0.205] # LiDAR在base系中的三维坐标
  lidar2base_R: [1,  0,  0,  # 从LiDAR坐标系旋转到base坐标系的旋转矩阵
                 0,  -1,  0,
                 0,  0,  -1]


publish:
  path_en:  true
  scan_publish_en:  true       # false: close all the point cloud output
  dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
  scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
  pcd_save_en: true
  max_frame_num: 1000
  log_dir_path: "/home/alpha/fastlio_airplane_ws/"
